marimari/marimari/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/',include("store.urls")),
    path('staff/',include("staff.urls")),
    path('logins/',include("logins.urls")),
    path('orders/',include("orders.urls")),
    path('categories/',include("categories.urls")),
    path('customer_account/',include("customer_account.urls")),
    path('api/v1/payments/',include("payments.urls"))
    
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

marimari/orders/urls.py
from django.urls import path
from .views import *

app_name = "orders"

urlpatterns = [  
    path('cart/', cart,name = "cart"), 
    path('cart/add_to_cart/<int:id>', add_to_cart, name = "user_cart"),
    path('wishlist/', wishlist ,name = "wishlist"),
    path('wishlist/add_to_wishlist/<int:id>', add_to_wishlist,name = "user_wishlist"),
    # path("cart/quantity", cartQuantity ,name="quantity"),    
]

marimari/staff/urls.py
from django.urls import path
from .views import *



urlpatterns = [
    path('dashboard/', dashboard, name = "dashboard"),
    # path('signin/', signin,name = "signin"),
    # path('signout/', signout, name = "signout"),
    # path('customers/', customers ,name = "customers"),
    # path('customers/register/', registerCustomer ,name = "register-customer"),
]

marimari/store/urls.py
from django.urls import path
from .views import *
from categories.views import *

app_name="store"

urlpatterns = [
    path('index/', index, name = "index"),
    path('checkout/', checkout,name = "checkout"),
    path('details/<int:id>',product_details,name = "details"),   
    path("search/", SearchResultsView.as_view(), name="search"),
    path("category/<int:id>/",CategoryView.as_view(),name="category"),
    path("search/search-filter", searchFilter ,name="search-filter"),
    path("search/one", one ,name="one"),
    path("search/two", two ,name="two"),
    path("search/three", three ,name="three"),
    path("search/four", four ,name="four"),
    path("search/five", five ,name="five"), 
]

marimari/orders/models.py
from django.db import models

# Create your models here.

marimari/orders/forms.py
# from django import forms
# # https://blog.kwetuhub.com/creating-shopping-cart-views-shop-products-django-2-0-python-3-6/

# PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


# class CartAddProductForm(forms.Form):
#     quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
#     update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

marimari/orders/views.py
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render,  HttpResponseRedirect,redirect
from store.views import product_details
from staff.models import *
from django.contrib import messages
from django.db.models import Count, Avg, F, Sum
from django.db.models import Q
from django.views import View
from django.contrib.auth import models

# Create your views here.
def view(request):
  response = HttpResponse('device')
  response.set_cookie('device', 'cookie_value')


def add_to_wishlist(request, id):

    user_id = request.user.id
    product = get_object_or_404(Product, id=id)
    if product.user_wishlist.filter(id=user_id).exists():
        product.user_wishlist.remove(request.user)
        # messages.success(item has been removed from your wishlist")
    else:
        product.user_wishlist.add(request.user)  
        # messages.success(item has been added to your wishlist")
    return HttpResponseRedirect(request.META["HTTP_REFERER"])

def wishlist(request):
    product = Product.objects.all()    
    category = Category.objects.all()
    products = Product.objects.filter(user_wishlist=request.user)
    product_id = Product.objects.filter(user_cart=request.user)
    total = product_id.aggregate(data=Sum('product_cost'))
    discounts = product_id.aggregate(discounts=Sum('discounts'))

    context = {
         "products": product,
        'categories': category,
        "wishlist":products,
        'cart_products':product_id,
        'discounts':discounts,
        'sum_data':total,
        }
    return render(request, "wishlist.html", context)

def add_to_cart(request, id): 
    user_id = request.user.id
    product = get_object_or_404(Product, id=id)
    
    if product.user_cart.filter(id=user_id).exists():
        product.user_cart.remove(request.user)
        # messages.success(item has been removed from your cart")
    else:
        product.user_cart.add(request.user)  
        # messages.success(item has been added to your cart")
    return HttpResponseRedirect(request.META["HTTP_REFERER"])    
    
def cart(request):
    if request.method != 'POST':  
        product = Product.objects.all()  
        category = Category.objects.all()  
        product_id = Product.objects.filter(user_cart=request.user)
        products = Product.objects.filter(user_wishlist=request.user)
        total = product_id.aggregate(data=Sum(F('product_cost')- F('discounts')))
        discounts = product_id.aggregate(discounts=Sum('discounts')) 
        
        
        context = {
        "products": product,
        'sum_data':total,
        'discounts':discounts,     
        "cart_products": product_id,
        "wishlist":products,
        'categories': category, 
            }
        
        
        return render(request, 'cart.html', context) 
    else:
        quantity = int(request.POST['quantity_field'])  
        prod_id = int(request.POST['product-id'])
        if quantity and prod_id: 
            product = Product.objects.all()  
            product_id = Product.objects.filter(user_cart=request.user)
            total = product_id.aggregate(data=Sum(F('product_cost')- F('discounts')))
            discounts = product_id.aggregate(discounts=Sum('discounts'))
            
            context = {  
            "products": product,
            'product_qty':quantity,         
            'sum_data':total,
            "cart_products": product_id,
                }
            
            
            return render(request, 'cart.html', context) 
     
     
   
    

marimari/orders/templates/add-cart.html
{% extends "base.html" %}{% load static %}{% block content %}
<div class="row">
    {% for cart_add in cart_added %}
    <div class="col-sm-12 col-md-4 col-lg-3 p-2">
        {% include 'cart-item.html' %}
    </div>
    {%endfor%}
</div>
{% endblock %}

marimari/orders/templates/cart-item.html
{% load static %}
<div class="cart-container">
    <div class="cart">
        <div class="items">
            <div class="item" id="cart-items">
                <img src="{{product.image.url}}">
                <div class="item-info">
                    <h4 class="h4" style="color:black;">{{product.product_name}}</h4>
                    <a href="{% url 'store:details' product.id %}" class="details">More info</a>
                        {% include "cart-qty.html" %}
                    <h5 class="h5" style="color:black;">Ksh.{{product.product_cost}}</h5>
                    <a href="{% url 'orders:user_cart' product.id  %}" class="lead"class="btn btn-sm fw500"><i class="fa fa-trash" aria-hidden="true"></i><span>Remove</span></a>
                </div>
            </div>
        </div>                  
    </div>
</div>

marimari/orders/templates/cart-qty.html
{% load static %}
{% block css %}
<link type="text/css" rel="stylesheet" href="{% static 'css/cart.css'  %}" />
{% endblock %}
<br>
<div class="quantity buttons_added">
	<input type="button" value="-" class="minus">
  <input type="text" step="1" min="1" max="" name="quantity" value="1" title="Qty" class="input-text qty text" size="4" pattern="" inputmode="">
  <input type="button" value="+" class="plus">
</div>

marimari/orders/templates/cart-total.html
{% load static %}
    <p class="h4"><span>Shipping</span>Ksh. 300</p>   
    <p class="h4"> <span>Number of products in Cart</span>{{cart_products|length}}</p>  
    <p class="h4"><span>You save</span> Ksh. {{ discounts.discounts}}</p>      
    <p class="h4"><span>TOTAL PRICE is</span> Ksh. {{ sum_data.data}}</p>
  

marimari/orders/templates/cart.html
{% extends 'base.html' %} {% load static %} {%  block 'css' %} {% endblock %}{% block 'content' %}
    <!-- CART SECTION -->
   <div class="row">
       <div class="container">
            <div  class="col-md-7">
                <h4 class="h4 text-center p-3">Manage your cart</h4>
                <hr>
                {% if cart_products %}
                    {% for product in cart_products %}
                        {% include 'cart-item.html' %}
                    {% endfor %}
                {% else %}
                    <p class="card-text text-center">no products have been added to the cart yet</p>
                {% endif %}
            </div>
            <div class="col-md-5">
                <h4 class="h4 text-center p-3">Cart Summary</h4>
                <hr>
                <div class="cart-total">
                    {% include 'cart-total.html' %}
                    <a href="{% url 'store:checkout' %}">Checkout <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
       </div>
   </div>
<!-- items you like section -->
 <!-- items you like section -->
 <div class="container">
    <div class="row">
        <div class="col-md-12 ">
            <div class="section-title ">
                <h3 class="title h3">More Products</h3>
                <div class="section-nav ">
                    <ul class="section-tab-nav tab-nav ">
                        <li class="active "><a data-toggle="tab " href="#tab2">Laptops</a></li>
                        <li><a data-toggle="tab " href="#tab2 ">Smartphones</a></li>
                        <li><a data-toggle="tab " href="#tab2 ">Cameras</a></li>
                        <li><a data-toggle="tab " href="#tab2 ">Accessories</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="row">
                <div class="products-tabs">

                    <div id="tab1" class="tab-pane active">
                        <div class="products-slick" data-nav="#slick-nav-1">
                        {% for product in products %}
                            {% include 'product.html' %}
                        {% endfor %}
                        </div>
                        <div id="slick-nav-1 " class="products-slick-nav "></div>
                    </div>

                </div>
            </div>
        </div>
    </div>
 </div>
   {% endblock %}
   {% block scripts %}
    {% endblock %}

marimari/orders/templates/widget.html
{% load static %}
<div class="product-widget product-under">
    <div class="product-img">
        <img src="{{product.image.url}}" alt="">
    </div>
    <div class="product-body">
        <h3 class="product-name h3"><a href="{% url 'store:details' product.id %}">{{product.product_name}}</a></h3>
        {% if products %}
            <p id="demo"></p>
        {% endif %}
        <h4 class="product-price">Ksh.{{product.product_cost}}</h4>
    </div>
    <a href="{% url 'orders:user_cart' product.id  %}" class="delete"><i class="fa fa-close"></i></a>
</div>

marimari/orders/templates/wishlist-item.html
{% load static %}
<div class="cart-container">
    <div class="cart">
        <div class="items">
            <div class="item">
                <img src="{{product.image.url}}">
                <div class="item-info">
                    <h4 class="h4 item-name" style="color:black;">{{product.product_name}}</h4>
                    <a href="{% url 'store:details' product.id %}" class="details">More info</a>
                    <h5 class="h5"  style="color:black;">KES.{{product.product_cost}}</h5>
                    <p>{{product.description}}<p>
                    <a href="{% url 'orders:user_wishlist' product.id  %}" class="lead"class="btn btn-sm fw500"><i class="fa fa-trash" aria-hidden="true"></i><span>Remove</span></a>
                </div>
            </div>
        </div>                  
    </div>
</div>

marimari/orders/templates/wishlist.html
{% extends 'base.html' %} {% load static %} {% block 'title' %}MariMari online shop{% endblock %}{% block 'content' %}
    <div class="row">
        <div class="container">
            <div class="col-md-7">
                <h4 class="lead text-center p-3">Manage your wishlist</h4>
                    <hr>
                {% if wishlist %}
                    {% for product in wishlist %}
                        {% include 'wishlist-item.html' %}
                    {% endfor %}
                {% else %}
                <p class="card-text text-center">no products have been added to the wishlist yet</p>
                {% endif %}
        
            </div>
            <div class="col-md-5">
                <h4 class="lead text-center p-3">Summary</h4>
                <hr>
                <div class="cart-total">
                
                    <p>
                        <span>Number of items</span>
                        <span>{{ wishlist|length }}</span>
                    </p>
                    <p>
                        <span>Discount</span>
                        <span>Ksh.{{ discounts.discounts}}</span>
                    </p>
                    <p>
                        <span>TOTAL PRICE</span>
                        <span>Ksh. {{ sum_data.data}}</span>
                    </p>
                    <a href="{% url 'store:checkout' %}">Add to Cart<i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="section ">

        <div class="container">
    
            <div class="row ">
                <div class="col-md-12 ">
                    <div class="section-title ">
                        <h3 class="title h3">You may also like</h3>
                        <div class="section-nav ">
                            <ul class="section-tab-nav tab-nav ">
                                <li class="active "><a data-toggle="tab " href="#tab2">Laptops</a></li>
                                <li><a data-toggle="tab " href="#tab2 ">Smartphones</a></li>
                                <li><a data-toggle="tab " href="#tab2 ">Cameras</a></li>
                                <li><a data-toggle="tab " href="#tab2 ">Accessories</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-12 ">
                    <div class="row ">
                        <div class="products-tabs ">
    
                            <div id="tab2 " class="tab-pane fade in active ">
                                <div class="products-slick " data-nav="#slick-nav-2 ">
                                    {% for product in products %}
                                        {% include 'product.html' %}
                                    {% endfor %}
                                </div>
                                <div id="slick-nav-2 " class="products-slick-nav "></div>
                            </div>
    
                        </div>
                    </div>
                </div>
    
            </div>
    
        </div>
    
    </div>

{% endblock %}