marimari/logins/urls.py
from django.urls import path
from .views import *
from logins import views
  
  
  
urlpatterns = [
    path('logins/about/', about,name = "about"),
    path('home/', home, name = "home"),
    path('logins/verify/', verification, name = "verify"),
    path('signout/', signout,name = "signout"),
    path('signin/', signin,name = "signin"),
    path('register/', register,name = "register"),    
]

marimari/marimari/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/',include("store.urls")),
    path('staff/',include("staff.urls")),
    path('logins/',include("logins.urls")),
    path('orders/',include("orders.urls")),
    path('categories/',include("categories.urls")),
    path('customer_account/',include("customer_account.urls")),
    path('api/v1/payments/',include("payments.urls"))
    
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

marimari/staff/urls.py
from django.urls import path
from .views import *



urlpatterns = [
    path('dashboard/', dashboard, name = "dashboard"),
    # path('signin/', signin,name = "signin"),
    # path('signout/', signout, name = "signout"),
    # path('customers/', customers ,name = "customers"),
    # path('customers/register/', registerCustomer ,name = "register-customer"),
]

marimari/store/urls.py
from django.urls import path
from .views import *
from categories.views import *

app_name="store"

urlpatterns = [
    path('index/', index, name = "index"),
    path('checkout/', checkout,name = "checkout"),
    path('details/<int:id>',product_details,name = "details"),   
    path("search/", SearchResultsView.as_view(), name="search"),
    path("category/<int:id>/",CategoryView.as_view(),name="category"),
    path("search/search-filter", searchFilter ,name="search-filter"),
    path("search/one", one ,name="one"),
    path("search/two", two ,name="two"),
    path("search/three", three ,name="three"),
    path("search/four", four ,name="four"),
    path("search/five", five ,name="five"), 
]

marimari/logins/models.py
from django.db import models

# Create your models here.

marimari/logins/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


        

def about(request):
    return render(request,"about.html")
   
def home(request):
    return render (request,"home.html")

def verification(request):
    return render (request,"verification.html")

def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("signin")

    else:
        form = UserCreationForm()
    return render(request,"register.html", {"form":form})

# def registerCustomer(request):
#     forms =CustomersForm()
#     if request.method == 'POST':
#         form = CustomersForm(request.POST)
#         if form.is_valid():
#           form.save()      
#         return HttpResponseRedirect("staff/signin/")


def signin(request):
    if request.method == "POST":
        form_data=request.POST
        username = form_data['username']
        password = form_data['password']  
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
                user = authenticate(username=username, password=password)
                login(request, user)
                print("DATA USERNAME={} PASSWORD={}".format(username, password))
            
                return redirect('/store/index/')
           
    else:
        form = AuthenticationForm()
    return render(request,"signin.html", {"form":form})

def signout(request):
    logout(request)
    return HttpResponseRedirect("/store/index/")

marimari/logins/templates/home.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>MariMare Online Shop</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/home.css' %}"/>
  
  </head>
  <body>
    <div class="container-fluid mb-3">
      {% comment %} navbar section {% endcomment %}

      <nav class="navbar navbar-light bg-muted">
        <div class="container-fluid">
          <h3 class="text-light">MariMare</h3>
          <form class="d-flex">
            <a href = "{% url 'store:index' %}">Shop</a>
            <a href = "{% url 'about' %}">About</a>
            <a href = "{% url 'register' %}" class="btn btn-dark border-white mx-3 btn-md" >Register</a>
          </form>
        </div>
      </nav>


      <div class ="row d-flex align-items-center justify-content-center mx-5">
        <div class ="col-md-5 ">
          <img src="{% static 'img/OIP.jpg' %}" alt=""  class="image-fluid mb-2 rounded-3 m-2" width= "24%" height = "12%">
          <img src="{% static 'img/lipa.png' %}" alt=""  class="image-fluid mb-2 rounded-3 m-2" width= "22%" height = "11%">
          <h1 class ="text-white mt-3"> We offer modern solutions for growing your business</h1>
          <p class ="lead text-white mt-4 border-top border-white">We are team of talented designers making websites with Bootstrap</p>
          
        </div>
        <div class ="col-md-6">
          <img src="{% static 'img/123.svg' %}" alt="" class="image-fluid" width= "100%" height = "100%">
        </div>
      </div> 
        <div class="text-white text-center bg-dark">
          © Copyright <strong><span>MariMare</span></strong>. All Rights Reserved || Designed by<a href="#">SaaSTechy</a>
        </div>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="" async defer></script>
  </body>
</html>

marimari/logins/templates/register.html
{% load static %}{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Sign Up</title>
    <meta content="" name="description">
    <meta content="" name="keywords">
    <link type="text/css" rel="stylesheet" href="{% static 'css/forms.css' %}" />
    <link rel="stylesheet" href="{% static 'css/home.css' %}"/>
</head>

<body  class="w-100">
    <div class="container-fluid mb-3">
        {% comment %} navbar section {% endcomment %}
  
        <div class ="row d-flex align-items-center justify-content-center mx-5">
          <div class ="col-md-5 ">
            <h2 class ="text-white mt-3 h2"> We offer modern solutions for growing your business</h2>
            <img src="{% static 'img/OIP.jpg' %}" alt=""  class="image-fluid mb-2 rounded-3 m-2" width= "22%" height = "10.5%">
            <img src="{% static 'img/lipa.png' %}" alt=""  class="image-fluid mb-2 rounded-3 m-2" width= "22%" height = "11%">
            <p class ="lead text-white mt-4 border-top border-white">We are team of talented designers making websites with Bootstrap</p>
            <div class="container">  
                 <form method="POST" class="text-white">
                     {% csrf_token %}
                     {% for hidden in form.hidden_fields %}
                         {{ hidden }}
                     {% endfor %}
         
                     {% for field in form.visible_fields %}
                     <div class="form-group">
                         <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                         {{ field|add_class:'form-control' }}
                         {% for error in field.errors %}
                         <span class="help-block">{{ error }}</span>
                         {% endfor %}
                     </div>
                     {% endfor %}
                     <div class="form-group text-center">
                         <button type="submit" class="btn btn-danger w-100 my-2">
                         <span class="glyphicon glyphicon-ok"></span> Create Account
                         </button>
                         <span  class="text-white">If you already have an account click</span>
                         <a href="{% url 'signin' %}" class="link-warning">Sign In</a>
                     </div>
                 </form>
                
                 
            </div>
          </div>
          <div class ="col-md-6">
            <img src="{% static 'img/123.svg' %}" alt="" class="image-fluid" width= "100%" height = "100%">
          </div>
        </div> 
          <div class="text-white text-center bg-dark">
            © Copyright <strong><span>MariMare</span></strong>. All Rights Reserved || Designed by<a href="#">SaaSTechy</a>
          </div>
    </div>
   
</body>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="" async defer></script>
</html>

marimari/logins/templates/signin.html
{% load static %} {% load widget_tweaks %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="sir steven osiru">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Signin</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sign-in/">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/home.css' %}"/>
    <link type="text/css" rel="stylesheet" href="{% static 'css/forms.css' %}" />
</head>

<body>
    <div class="container-fluid mb-3">
        {% comment %} navbar section {% endcomment %}
        <div class ="row d-flex align-items-center justify-content-center mx-5">
          <div class ="col-md-5 ">
            <h333333 class ="text-white mt-3 h3">Get 30% off on each product Shopping made easy by marimare </h333333>
            <img src="{% static 'img/OIP.jpg' %}" alt=""  class="image-fluid mb-2 rounded-3 m-2" width= "22%" height = "10.5%">
            <img src="{% static 'img/lipa.png' %}" alt=""  class="image-fluid mb-2 rounded-3 m-2" width= "22%" height = "11%">
            <p class ="lead text-white mt-4 border-top border-white">Please fill the form below to signin</p>
            <div class="container">  
                <form method="POST" class="text-white">
                    {% csrf_token %}
                    {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                    {% endfor %}
            
                    {% for field in form.visible_fields %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field|add_class:'form-control' }}
                        {% for error in field.errors %}
                        <span class="help-block">{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% endfor %}
                    <div class="form-group text-center">
                        <button type="submit" class="btn btn-danger w-100 my-2">
                        <span class="glyphicon glyphicon-ok"></span>Sign In
                        </button>
                        <span class="text-white">If you do not have an account click</span>
                        <a href="{% url 'register' %}" class="link-warning">Register</a>
                    </div>   
                </form>              
                 
            </div>
          </div>
          <div class ="col-md-6">
            <img src="{% static 'img/123.svg' %}" alt="" class="image-fluid" width= "100%" height = "100%">
          </div>
        </div> 
          <div class="text-white text-center bg-dark">
            © Copyright <strong><span>MariMare</span></strong>. All Rights Reserved || Designed by<a href="#">SaaSTechy</a>
          </div>
    </div>
</body>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="" async defer></script>

</html>

marimari/logins/templates/verification.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>verify</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
        <link type="text/css" rel="stylesheet" href="{% static 'css/forms.css' %}" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    </head>
    <body>
    <div class="container w-25 mt-4">
        <p class="lead ml-5 mt-5">Verify your Phone Number</hp>
        <form>
            <div class="mb-3">
              <label for="user_number" class="form-label">Enter Phone Number</label>
              <input type="number" placeholder = "+254071234567" class="form-control" id="user_number" aria-describedby="phone_numberHelp">
            </div>
            <div class="mb-3">
              <label for="otp" class="form-label">SMS OTP</label>
              <input type="number" class="form-control" id="otp">
            </div>
            
            <div class="form-group text-end">
                <button href="{% url 'store:index' %}" type="submit" class="btn btn-danger w-100 my-2">
                <span class="glyphicon glyphicon-ok"></span>Confirm
                </button>
                <a href="{% url 'store:index' %}" class="link-danger">Send SMS</a>
            </div>
            <div id="phone_numberHelp" class="form-text">The information provided above is Confidential</div>
            <a href="{% url 'register' %}" class="link-danger"><i class="fa fa-backward" aria-hidden="true"></i>back</a>
        </form>
    </div>
        
        <script src="" async defer></script>
    </body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</html>