marimari/categories/urls.py
from unicodedata import category
from django.urls import path
from .views import *


app_name = "categories"
  
  
urlpatterns = [
  path("category/<int:id>/",categoryNav, name="prods-category")
]

marimari/marimari/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/',include("store.urls")),
    path('staff/',include("staff.urls")),
    path('logins/',include("logins.urls")),
    path('orders/',include("orders.urls")),
    path('categories/',include("categories.urls")),
    path('customer_account/',include("customer_account.urls")),
    path('api/v1/payments/',include("payments.urls"))
    
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

marimari/staff/urls.py
from django.urls import path
from .views import *



urlpatterns = [
    path('dashboard/', dashboard, name = "dashboard"),
    # path('signin/', signin,name = "signin"),
    # path('signout/', signout, name = "signout"),
    # path('customers/', customers ,name = "customers"),
    # path('customers/register/', registerCustomer ,name = "register-customer"),
]

marimari/store/urls.py
from django.urls import path
from .views import *
from categories.views import *

app_name="store"

urlpatterns = [
    path('index/', index, name = "index"),
    path('checkout/', checkout,name = "checkout"),
    path('details/<int:id>',product_details,name = "details"),   
    path("search/", SearchResultsView.as_view(), name="search"),
    path("category/<int:id>/",CategoryView.as_view(),name="category"),
    path("search/search-filter", searchFilter ,name="search-filter"),
    path("search/one", one ,name="one"),
    path("search/two", two ,name="two"),
    path("search/three", three ,name="three"),
    path("search/four", four ,name="four"),
    path("search/five", five ,name="five"), 
]

marimari/categories/models.py
from django.db import models

# Create your models here.

marimari/categories/views.py
from itertools import product
from sys import setswitchinterval
from urllib import request
from django.views import View
from staff.models import *
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.db.models import Q
from django.views.generic import TemplateView, ListView , DetailView


app_name="categories"

# Create your views here.
class SearchResultsView(ListView):
    model = Product
    template_name = "search.html"
    def get_queryset(self):  # new
        query = self.request.GET["search_value"]
        category = int(self.request.GET["category"])
        
        
        if category == 0:
            object_list = Product.objects.all()
        
        if query and not category:
            object_list = Product.objects.filter(
                Q(product_name__icontains=query)
            )
        elif category and not query:
            object_list = Product.objects.filter(
                Q(category__id=category)
            )
            
        else:
            object_list = Product.objects.filter(
                Q(category__id=category), Q(product_name__icontains=query)
            )
      
        return object_list
    
    def get_context_data(self,*args, **kwargs):
        context = super(SearchResultsView, self).get_context_data(*args,**kwargs)
        context['categories'] = Category.objects.all()
        return context
    
class CategoryView(View):
    def get(self, request, id):
        category = Category.objects.filter(id=id).first()
        products = Product.objects.filter(category=category)

        context ={
            'categories':category,
            'products':products,
         }
        return render(request, 'categories.html', context)
   
def searchFilter(request):  
    if request.user.is_authenticated: 
        category = Category.objects.all() 
        min_price = request.GET['min-price']
        max_price = request.GET['max-price']
        productsFilter = Product.objects.filter(product_cost__range=(min_price, max_price))
        product_id = Product.objects.filter(user_cart=request.user) 
        total = product_id.aggregate(data=Sum(F('product_cost')-F('discounts')))
        products = Product.objects.filter(user_wishlist=request.user)
        context = {
                'categories':category,
                'min_price': min_price,
                'max_price': max_price,
                'object_list': productsFilter, 
                "cart_products": product_id,  
                'sum_data':total,
                "wishlist":products,     
            }
        
        return render(request, 'search.html', context)
    else:
        category = Category.objects.all() 
        min_price = request.GET['min-price']
        max_price = request.GET['max-price']
        productsFilter = Product.objects.filter(product_cost__range=(min_price, max_price))
        context = {
                'categories':category,
                'min_price': min_price,
                'max_price': max_price,
                'object_list': productsFilter, 
            }
        
        return render(request, 'search.html', context)

    
def one(request):
    if request.user.is_authenticated:
        category = Category.objects.all() 
        products = Product.objects.filter(user_wishlist=request.user)
        product_id = Product.objects.filter(user_cart=request.user) 
        price = Product.objects.filter(product_cost__lte = 10000)
        context={
            "cart_products": product_id,  
            'categories':category,
            "wishlist":products,  
            "object_list":price
        }
        return render(request,'search.html', context) 
    else:
        category = Category.objects.all() 
        price = Product.objects.filter(product_cost__lte = 10000)
        context={
            'categories':category,
            "object_list":price
        }
        return render(request,'search.html', context) 
    
def two(request):
    if request.user.is_authenticated:
        category = Category.objects.all() 
        products = Product.objects.filter(user_wishlist=request.user)
        product_id = Product.objects.filter(user_cart=request.user) 
        price = Product.objects.filter(product_cost__gt = 10000, product_cost__lte = 50000)
        context={
            "cart_products": product_id,  
            'categories':category,
            "wishlist":products, 
            "object_list":price
        }
        return render(request,'search.html', context) 
    else:
        category = Category.objects.all() 
        price = Product.objects.filter(product_cost__gt = 10000, product_cost__lte = 50000)
        context={
            'categories':category,
            "object_list":price
        }
        return render(request,'search.html', context) 
    
def three(request):
    if request.user.is_authenticated:
        category = Category.objects.all() 
        products = Product.objects.filter(user_wishlist=request.user)
        product_id = Product.objects.filter(user_cart=request.user) 
        price = Product.objects.filter(product_cost__gt = 50000, product_cost__lte = 100000)
        context={
            "cart_products": product_id,  
            'categories':category,
            "wishlist":products,
            "object_list":price
        }
        return render(request,'search.html', context) 
    else:
        category = Category.objects.all() 
        price = Product.objects.filter(product_cost__gt = 50000, product_cost__lte = 100000)
        context={
            'categories':category,
            "object_list":price
        }
        return render(request,'search.html', context) 
         
    
def four(request):
    if request.user.is_authenticated:
        category = Category.objects.all() 
        products = Product.objects.filter(user_wishlist=request.user)
        product_id = Product.objects.filter(user_cart=request.user) 
        price = Product.objects.filter(product_cost__gt = 100000, product_cost__lte = 150000)
        context={

            "cart_products": product_id,  
            'categories':category,
            "wishlist":products,
            "object_list":price
        }
        return render(request,'search.html', context) 
    else:
        category = Category.objects.all() 
        price = Product.objects.filter(product_cost__gt = 100000, product_cost__lte = 150000)
        context={
            'categories':category,
            "object_list":price
        }
        return render(request,'search.html', context) 
    
def five(request):
    if request.user.is_authenticated:
        category = Category.objects.all() 
        products = Product.objects.filter(user_wishlist=request.user)
        product_id = Product.objects.filter(user_cart=request.user) 
        price = Product.objects.filter(product_cost__gt = 150000)
        context={
            "cart_products": product_id,  
            'categories':category,
            "wishlist":products,
            "object_list":price
        }
        return render(request,'search.html', context) 
    else:
        category = Category.objects.all() 
        price = Product.objects.filter(product_cost__gt = 150000)
        context={
            'categories':category,
            "object_list":price,
        }
        return render(request,'search.html', context) 
    
def categoryNav(request, id):
    category = Category.objects.all()
    name = Category.objects.filter(id=id)
    context = {
        'cat':name,
        'categories':category,
    }
    return render(request,'search.html', context) 
    




   
    
   

marimari/categories/templates/categories.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
{% endblock %}
{% block 'content' %}
<h1 class="head">{{ category.category_name }}</h1>
<h3>Products for this category</h3>
<div>
    {% for product in products %}
    <div>
        <h5>{{ product.title }}<h5/>
        <div>{{ product.description }}</div>
        <img src="{{ product.image.url }}"/>
    </div>
    {% endfor %}
</div>
{% endblock %}
{% block scripts %}
{% endblock %}

marimari/categories/templates/search.html
{% extends 'base.html' %}
{% load static %}
{%block title %}
    Search
{% endblock %}
{% block css %}
{% endblock %}
{% block 'content' %}
    <div class="row">
        <div class="container">
            <div class="col-md-7">
                <h4 class="h4 text-center">Search results</h4>
                </hr>
                {% if object_list %}
                {% for product in object_list %}
                    {% include 'search_item.html' %}
                {% endfor %}
                {% else %}
                <p class="card-text text-center">search not found</p>
                {% endif %}
            </div>
            <div class="col-md-5">
                <div class="container-fluid">
                    <div class="filter-content">
                        <h3 class="h3 filter-title">Prices Filter</h3>
                        <form action="{% url 'store:search-filter' %}" class="filter-form" method="GET">
                            <input type="number" class="search-filter" name="max-price" placeholder="Max-price">
                            <input type="number" class="search-filter" name="min-price" placeholder="Min-price">
                            <button type="submit" class="btn button-filter">Filter<i class="fa fa-arrow-circle-right"></i></button>
                        </form>
                        <div class="cart-total filter-items">
                            <p>
                                <a href="{% url 'store:one'   %}" class="price-list">below KES 10000 <i class="fas fa-hand-point-right bg-danger"></i></a>
                            </p>
                            <p>
                                <a href="{% url 'store:two'  %}"  class="price-list">KES 10001-50000<i class="fas fa-hand-point-right"></i></a>
                            </p>
                            <p>
                                <a href="{% url 'store:three'  %}"  class="price-list">KES 50001-100000 <i class="fas fa-hand-point-right"></i></a>
                            </p>
                            <p>
                                <a href="{% url 'store:four'  %}"  class="price-list">KES 100001-150000 <i class="fas fa-hand-point-right"></i></a>
                            </p>
                            <p>
                                <a href="{% url 'store:five'  %}"  class="price-list">KES 150001 and above <i class="fas fa-hand-point-right"></i></a>
                            </p>               
                        </div>
                    </div>
                </div>
            </div>
           </div>
        <div>
    </div>
       
{% endblock %}
{% block scripts %}
{% endblock %}

marimari/categories/templates/search_item.html
{% load static %}
<div class="cart-container">
    <div class="cart">
        <div class="items">
            <div class="item">
                <img src="{{product.image.url}}">
                <div class="item-info">
                    <h4 class="h4 item-name" style="color:black;">{{product.product_name}}</h4>
                    <a href="{% url 'store:details' product.id %}" class="details">More info</a>
                    <h5 class="h5"  style="color:black;">KES.{{product.product_cost}}</h5>
                    <p>{{product.description}}<p>
                </div>
            </div>
        </div>                  
    </div>
</div>